package com.incremensa.drupaldb.model;
// Generated May 11, 2011 9:15:58 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * FieldRevisionBody generated by hbm2java
 */
@Entity
@Table(name="field_revision_body"
    ,catalog="bitnami_drupal7"
)
public class FieldRevisionBody  implements java.io.Serializable {


     private FieldRevisionBodyId id;
     private String bundle;
     private String bodyValue;
     private String bodySummary;
     private String bodyFormat;

    public FieldRevisionBody() {
    }

	
    public FieldRevisionBody(FieldRevisionBodyId id, String bundle) {
        this.id = id;
        this.bundle = bundle;
    }
    public FieldRevisionBody(FieldRevisionBodyId id, String bundle, String bodyValue, String bodySummary, String bodyFormat) {
       this.id = id;
       this.bundle = bundle;
       this.bodyValue = bodyValue;
       this.bodySummary = bodySummary;
       this.bodyFormat = bodyFormat;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="entityType", column=@Column(name="entity_type", nullable=false, length=128) ), 
        @AttributeOverride(name="entityId", column=@Column(name="entity_id", nullable=false) ), 
        @AttributeOverride(name="revisionId", column=@Column(name="revision_id", nullable=false) ), 
        @AttributeOverride(name="deleted", column=@Column(name="deleted", nullable=false) ), 
        @AttributeOverride(name="delta", column=@Column(name="delta", nullable=false) ), 
        @AttributeOverride(name="language", column=@Column(name="language", nullable=false, length=32) ) } )
    public FieldRevisionBodyId getId() {
        return this.id;
    }
    
    public void setId(FieldRevisionBodyId id) {
        this.id = id;
    }
    
    @Column(name="bundle", nullable=false, length=128)
    public String getBundle() {
        return this.bundle;
    }
    
    public void setBundle(String bundle) {
        this.bundle = bundle;
    }
    
    @Column(name="body_value", columnDefinition="longtext")
    public String getBodyValue() {
        return this.bodyValue;
    }
    
    public void setBodyValue(String bodyValue) {
        this.bodyValue = bodyValue;
    }
    
    @Column(name="body_summary", columnDefinition="longtext")
    public String getBodySummary() {
        return this.bodySummary;
    }
    
    public void setBodySummary(String bodySummary) {
        this.bodySummary = bodySummary;
    }
    
    @Column(name="body_format")
    public String getBodyFormat() {
        return this.bodyFormat;
    }
    
    public void setBodyFormat(String bodyFormat) {
        this.bodyFormat = bodyFormat;
    }




}


