package com.incremensa.drupaldb.model;
// Generated May 14, 2011 8:41:40 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * FieldDataFieldTechconcept generated by hbm2java
 */
@Entity
@Table(name="field_data_field_techconcept"
    ,catalog="bitnami_drupal7"
)
public class FieldDataFieldTechconcept  implements java.io.Serializable {


     private FieldDataFieldTechconceptId id;
     private String bundle;
     private Integer revisionId;
     private Integer fieldTechconceptTid;

    public FieldDataFieldTechconcept() {
    }

	
    public FieldDataFieldTechconcept(FieldDataFieldTechconceptId id, String bundle) {
        this.id = id;
        this.bundle = bundle;
    }
    public FieldDataFieldTechconcept(FieldDataFieldTechconceptId id, String bundle, Integer revisionId, Integer fieldTechconceptTid) {
       this.id = id;
       this.bundle = bundle;
       this.revisionId = revisionId;
       this.fieldTechconceptTid = fieldTechconceptTid;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="entityType", column=@Column(name="entity_type", nullable=false, length=128) ), 
        @AttributeOverride(name="entityId", column=@Column(name="entity_id", nullable=false) ), 
        @AttributeOverride(name="deleted", column=@Column(name="deleted", nullable=false) ), 
        @AttributeOverride(name="delta", column=@Column(name="delta", nullable=false) ), 
        @AttributeOverride(name="language", column=@Column(name="language", nullable=false, length=32) ) } )
    public FieldDataFieldTechconceptId getId() {
        return this.id;
    }
    
    public void setId(FieldDataFieldTechconceptId id) {
        this.id = id;
    }
    
    @Column(name="bundle", nullable=false, length=128)
    public String getBundle() {
        return this.bundle;
    }
    
    public void setBundle(String bundle) {
        this.bundle = bundle;
    }
    
    @Column(name="revision_id")
    public Integer getRevisionId() {
        return this.revisionId;
    }
    
    public void setRevisionId(Integer revisionId) {
        this.revisionId = revisionId;
    }
    
    @Column(name="field_techconcept_tid")
    public Integer getFieldTechconceptTid() {
        return this.fieldTechconceptTid;
    }
    
    public void setFieldTechconceptTid(Integer fieldTechconceptTid) {
        this.fieldTechconceptTid = fieldTechconceptTid;
    }




}


