package com.incremensa.drupaldb.model;
// Generated May 11, 2011 9:15:58 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FieldDataBodyId generated by hbm2java
 */
@Embeddable
public class FieldDataBodyId  implements java.io.Serializable {


     private String entityType;
     private int entityId;
     private byte deleted;
     private int delta;
     private String language;

    public FieldDataBodyId() {
    }

    public FieldDataBodyId(String entityType, int entityId, byte deleted, int delta, String language) {
       this.entityType = entityType;
       this.entityId = entityId;
       this.deleted = deleted;
       this.delta = delta;
       this.language = language;
    }
   

    @Column(name="entity_type", nullable=false, length=128)
    public String getEntityType() {
        return this.entityType;
    }
    
    public void setEntityType(String entityType) {
        this.entityType = entityType;
    }

    @Column(name="entity_id", nullable=false)
    public int getEntityId() {
        return this.entityId;
    }
    
    public void setEntityId(int entityId) {
        this.entityId = entityId;
    }

    @Column(name="deleted", nullable=false)
    public byte getDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(byte deleted) {
        this.deleted = deleted;
    }

    @Column(name="delta", nullable=false)
    public int getDelta() {
        return this.delta;
    }
    
    public void setDelta(int delta) {
        this.delta = delta;
    }

    @Column(name="language", nullable=false, length=32)
    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FieldDataBodyId) ) return false;
		 FieldDataBodyId castOther = ( FieldDataBodyId ) other; 
         
		 return ( (this.getEntityType()==castOther.getEntityType()) || ( this.getEntityType()!=null && castOther.getEntityType()!=null && this.getEntityType().equals(castOther.getEntityType()) ) )
 && (this.getEntityId()==castOther.getEntityId())
 && (this.getDeleted()==castOther.getDeleted())
 && (this.getDelta()==castOther.getDelta())
 && ( (this.getLanguage()==castOther.getLanguage()) || ( this.getLanguage()!=null && castOther.getLanguage()!=null && this.getLanguage().equals(castOther.getLanguage()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEntityType() == null ? 0 : this.getEntityType().hashCode() );
         result = 37 * result + this.getEntityId();
         result = 37 * result + this.getDeleted();
         result = 37 * result + this.getDelta();
         result = 37 * result + ( getLanguage() == null ? 0 : this.getLanguage().hashCode() );
         return result;
   }   


}


