package com.incremensa.drupaldb.model;
// Generated May 14, 2011 6:33:54 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NodeCommentStatistics generated by hbm2java
 */
@Entity
@Table(name="node_comment_statistics"
    ,catalog="bitnami_drupal7"
)
public class NodeCommentStatistics  implements java.io.Serializable {


     private int nid;
     private int cid;
     private int lastCommentTimestamp;
     private String lastCommentName;
     private int lastCommentUid;
     private int commentCount;

    public NodeCommentStatistics() {
    }

	
    public NodeCommentStatistics(int nid, int cid, int lastCommentTimestamp, int lastCommentUid, int commentCount) {
        this.nid = nid;
        this.cid = cid;
        this.lastCommentTimestamp = lastCommentTimestamp;
        this.lastCommentUid = lastCommentUid;
        this.commentCount = commentCount;
    }
    public NodeCommentStatistics(int nid, int cid, int lastCommentTimestamp, String lastCommentName, int lastCommentUid, int commentCount) {
       this.nid = nid;
       this.cid = cid;
       this.lastCommentTimestamp = lastCommentTimestamp;
       this.lastCommentName = lastCommentName;
       this.lastCommentUid = lastCommentUid;
       this.commentCount = commentCount;
    }
   
     @Id 
    
    @Column(name="nid", unique=true, nullable=false)
    public int getNid() {
        return this.nid;
    }
    
    public void setNid(int nid) {
        this.nid = nid;
    }
    
    @Column(name="cid", nullable=false)
    public int getCid() {
        return this.cid;
    }
    
    public void setCid(int cid) {
        this.cid = cid;
    }
    
    @Column(name="last_comment_timestamp", nullable=false)
    public int getLastCommentTimestamp() {
        return this.lastCommentTimestamp;
    }
    
    public void setLastCommentTimestamp(int lastCommentTimestamp) {
        this.lastCommentTimestamp = lastCommentTimestamp;
    }
    
    @Column(name="last_comment_name", length=60)
    public String getLastCommentName() {
        return this.lastCommentName;
    }
    
    public void setLastCommentName(String lastCommentName) {
        this.lastCommentName = lastCommentName;
    }
    
    @Column(name="last_comment_uid", nullable=false)
    public int getLastCommentUid() {
        return this.lastCommentUid;
    }
    
    public void setLastCommentUid(int lastCommentUid) {
        this.lastCommentUid = lastCommentUid;
    }
    
    @Column(name="comment_count", nullable=false)
    public int getCommentCount() {
        return this.commentCount;
    }
    
    public void setCommentCount(int commentCount) {
        this.commentCount = commentCount;
    }




}


