package com.incremensa.drupaldb.model;
// Generated May 11, 2011 9:15:58 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * NodeRevision generated by hbm2java
 */
@Entity
@Table(name="node_revision"
    ,catalog="bitnami_drupal7"
)
public class NodeRevision  implements java.io.Serializable {


     private Integer vid;
     private int timestamp;
     private int nid;
     private int uid;
     private String title;
     private String log;
     private int status;
     private int comment;
     private int promote;
     private int sticky;

    public NodeRevision() {
    }

    public NodeRevision(int nid, int uid, String title, String log, int status, int comment, int promote, int sticky) {
       this.nid = nid;
       this.uid = uid;
       this.title = title;
       this.log = log;
       this.status = status;
       this.comment = comment;
       this.promote = promote;
       this.sticky = sticky;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="vid", unique=true, nullable=false)
    public Integer getVid() {
        return this.vid;
    }
    
    public void setVid(Integer vid) {
        this.vid = vid;
    }
    @Version
    @Column(name="timestamp", nullable=false)
    public int getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(int timestamp) {
        this.timestamp = timestamp;
    }
    
    @Column(name="nid", nullable=false)
    public int getNid() {
        return this.nid;
    }
    
    public void setNid(int nid) {
        this.nid = nid;
    }
    
    @Column(name="uid", nullable=false)
    public int getUid() {
        return this.uid;
    }
    
    public void setUid(int uid) {
        this.uid = uid;
    }
    
    @Column(name="title", nullable=false)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    
    @Column(name="log", nullable=false, columnDefinition="longtext")
    public String getLog() {
        return this.log;
    }
    
    public void setLog(String log) {
        this.log = log;
    }
    
    @Column(name="status", nullable=false)
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    
    @Column(name="comment", nullable=false)
    public int getComment() {
        return this.comment;
    }
    
    public void setComment(int comment) {
        this.comment = comment;
    }
    
    @Column(name="promote", nullable=false)
    public int getPromote() {
        return this.promote;
    }
    
    public void setPromote(int promote) {
        this.promote = promote;
    }
    
    @Column(name="sticky", nullable=false)
    public int getSticky() {
        return this.sticky;
    }
    
    public void setSticky(int sticky) {
        this.sticky = sticky;
    }




}


