package com.incremensa.drupaldb.model;
// Generated May 15, 2011 11:33:29 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sequences generated by hbm2java
 */
@Entity
@Table(name="sequences"
    ,catalog="bitnami_drupal7"
)
public class Sequences  implements java.io.Serializable {


     private Integer value;

    public Sequences() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="value", unique=true, nullable=false)
    public Integer getValue() {
        return this.value;
    }
    
    public void setValue(Integer value) {
        this.value = value;
    }




}


