package com.incremensa.drupaldb.model;
// Generated May 11, 2011 9:15:58 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TaxonomyTermHierarchy generated by hbm2java
 */
@Entity
@Table(name="taxonomy_term_hierarchy"
    ,catalog="bitnami_drupal7"
)
public class TaxonomyTermHierarchy  implements java.io.Serializable {


     private TaxonomyTermHierarchyId id;

    public TaxonomyTermHierarchy() {
    }

    public TaxonomyTermHierarchy(TaxonomyTermHierarchyId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="tid", column=@Column(name="tid", nullable=false) ), 
        @AttributeOverride(name="parent", column=@Column(name="parent", nullable=false) ) } )
    public TaxonomyTermHierarchyId getId() {
        return this.id;
    }
    
    public void setId(TaxonomyTermHierarchyId id) {
        this.id = id;
    }




}


