package com.incremensa.drupaldb.model;
// Generated May 11, 2011 9:15:58 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TaxonomyVocabulary generated by hbm2java
 */
@Entity
@Table(name="taxonomy_vocabulary"
    ,catalog="bitnami_drupal7"
    , uniqueConstraints = @UniqueConstraint(columnNames="machine_name") 
)
public class TaxonomyVocabulary  implements java.io.Serializable {


     private Integer vid;
     private String name;
     private String machineName;
     private String description;
     private byte hierarchy;
     private String module;
     private int weight;

    public TaxonomyVocabulary() {
    }

	
    public TaxonomyVocabulary(String name, String machineName, byte hierarchy, String module, int weight) {
        this.name = name;
        this.machineName = machineName;
        this.hierarchy = hierarchy;
        this.module = module;
        this.weight = weight;
    }
    public TaxonomyVocabulary(String name, String machineName, String description, byte hierarchy, String module, int weight) {
       this.name = name;
       this.machineName = machineName;
       this.description = description;
       this.hierarchy = hierarchy;
       this.module = module;
       this.weight = weight;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="vid", unique=true, nullable=false)
    public Integer getVid() {
        return this.vid;
    }
    
    public void setVid(Integer vid) {
        this.vid = vid;
    }
    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="machine_name", unique=true, nullable=false)
    public String getMachineName() {
        return this.machineName;
    }
    
    public void setMachineName(String machineName) {
        this.machineName = machineName;
    }
    
    @Column(name="description", columnDefinition="longtext")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="hierarchy", nullable=false)
    public byte getHierarchy() {
        return this.hierarchy;
    }
    
    public void setHierarchy(byte hierarchy) {
        this.hierarchy = hierarchy;
    }
    
    @Column(name="module", nullable=false)
    public String getModule() {
        return this.module;
    }
    
    public void setModule(String module) {
        this.module = module;
    }
    
    @Column(name="weight", nullable=false)
    public int getWeight() {
        return this.weight;
    }
    
    public void setWeight(int weight) {
        this.weight = weight;
    }




}


