package com.incremensa.drupaldb.model;
// Generated May 11, 2011 9:15:58 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UrlAlias generated by hbm2java
 */
@Entity
@Table(name="url_alias"
    ,catalog="bitnami_drupal7"
)
public class UrlAlias  implements java.io.Serializable {


     private Integer pid;
     private String source;
     private String alias;
     private String language;

    public UrlAlias() {
    }

    public UrlAlias(String source, String alias, String language) {
       this.source = source;
       this.alias = alias;
       this.language = language;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="pid", unique=true, nullable=false)
    public Integer getPid() {
        return this.pid;
    }
    
    public void setPid(Integer pid) {
        this.pid = pid;
    }
    
    @Column(name="source", nullable=false)
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }
    
    @Column(name="alias", nullable=false)
    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }
    
    @Column(name="language", nullable=false, length=12)
    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }




}


