package com.incremensa.drupaldb.model;
// Generated May 11, 2011 9:15:58 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="bitnami_drupal7"
    , uniqueConstraints = @UniqueConstraint(columnNames="name") 
)
public class Users  implements java.io.Serializable {


     private int uid;
     private String name;
     private String pass;
     private String mail;
     private String theme;
     private String signature;
     private String signatureFormat;
     private int created;
     private int access;
     private int login;
     private byte status;
     private String timezone;
     private String language;
     private int picture;
     private String init;
     private byte[] data;

    public Users() {
    }

	
    public Users(int uid, String name, String pass, String theme, String signature, int created, int access, int login, byte status, String language, int picture) {
        this.uid = uid;
        this.name = name;
        this.pass = pass;
        this.theme = theme;
        this.signature = signature;
        this.created = created;
        this.access = access;
        this.login = login;
        this.status = status;
        this.language = language;
        this.picture = picture;
    }
    public Users(int uid, String name, String pass, String mail, String theme, String signature, String signatureFormat, int created, int access, int login, byte status, String timezone, String language, int picture, String init, byte[] data) {
       this.uid = uid;
       this.name = name;
       this.pass = pass;
       this.mail = mail;
       this.theme = theme;
       this.signature = signature;
       this.signatureFormat = signatureFormat;
       this.created = created;
       this.access = access;
       this.login = login;
       this.status = status;
       this.timezone = timezone;
       this.language = language;
       this.picture = picture;
       this.init = init;
       this.data = data;
    }
   
     @Id 
    
    @Column(name="uid", unique=true, nullable=false)
    public int getUid() {
        return this.uid;
    }
    
    public void setUid(int uid) {
        this.uid = uid;
    }
    
    @Column(name="name", unique=true, nullable=false, length=60)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="pass", nullable=false, length=128)
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    
    @Column(name="mail", length=254)
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    
    @Column(name="theme", nullable=false)
    public String getTheme() {
        return this.theme;
    }
    
    public void setTheme(String theme) {
        this.theme = theme;
    }
    
    @Column(name="signature", nullable=false)
    public String getSignature() {
        return this.signature;
    }
    
    public void setSignature(String signature) {
        this.signature = signature;
    }
    
    @Column(name="signature_format")
    public String getSignatureFormat() {
        return this.signatureFormat;
    }
    
    public void setSignatureFormat(String signatureFormat) {
        this.signatureFormat = signatureFormat;
    }
    
    @Column(name="created", nullable=false)
    public int getCreated() {
        return this.created;
    }
    
    public void setCreated(int created) {
        this.created = created;
    }
    
    @Column(name="access", nullable=false)
    public int getAccess() {
        return this.access;
    }
    
    public void setAccess(int access) {
        this.access = access;
    }
    
    @Column(name="login", nullable=false)
    public int getLogin() {
        return this.login;
    }
    
    public void setLogin(int login) {
        this.login = login;
    }
    
    @Column(name="status", nullable=false)
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }
    
    @Column(name="timezone", length=32)
    public String getTimezone() {
        return this.timezone;
    }
    
    public void setTimezone(String timezone) {
        this.timezone = timezone;
    }
    
    @Column(name="language", nullable=false, length=12)
    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }
    
    @Column(name="picture", nullable=false)
    public int getPicture() {
        return this.picture;
    }
    
    public void setPicture(int picture) {
        this.picture = picture;
    }
    
    @Column(name="init", length=254)
    public String getInit() {
        return this.init;
    }
    
    public void setInit(String init) {
        this.init = init;
    }
    
    @Column(name="data", columnDefinition="longblob")
    public byte[] getData() {
        return this.data;
    }
    
    public void setData(byte[] data) {
        this.data = data;
    }




}


