package com.incremensa.drupaldb.model;
// Generated May 11, 2011 9:15:58 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UsersRoles generated by hbm2java
 */
@Entity
@Table(name="users_roles"
    ,catalog="bitnami_drupal7"
)
public class UsersRoles  implements java.io.Serializable {


     private UsersRolesId id;

    public UsersRoles() {
    }

    public UsersRoles(UsersRolesId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="uid", column=@Column(name="uid", nullable=false) ), 
        @AttributeOverride(name="rid", column=@Column(name="rid", nullable=false) ) } )
    public UsersRolesId getId() {
        return this.id;
    }
    
    public void setId(UsersRolesId id) {
        this.id = id;
    }




}


